In [1]:
import numpy as np
import pandas as pd
import viz

## 1. How likely is it that you roll doubles when rolling two dice?

In [38]:
# Assume the dices are six sides and fair. 

n_trials = nrows = 1_000_000
n_dice = ncols = 2

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[3, 1],
       [2, 3],
       [1, 5],
       ...,
       [4, 4],
       [6, 3],
       [5, 5]])

In [39]:
boolean_roll_doubles = [rolls[i][0] == rolls[i][1] for i in range(0, nrows)]
pd.Series(boolean_roll_doubles).mean()

0.166589

## 2-a. If you flip 8 coins, what is the probability of getting exactly 3 heads? 

In [50]:
# Assume all the conis are fair coins

n_trials = nrows = 1_000_000
n_coins = ncols = 8

flips = np.random.choice(['Head', 'Tails'], n_trials * n_coins).reshape(nrows, ncols)
flips

array([['Head', 'Tails', 'Head', ..., 'Tails', 'Tails', 'Tails'],
       ['Head', 'Head', 'Tails', ..., 'Head', 'Head', 'Tails'],
       ['Head', 'Head', 'Tails', ..., 'Tails', 'Tails', 'Head'],
       ...,
       ['Head', 'Head', 'Tails', ..., 'Head', 'Head', 'Head'],
       ['Head', 'Head', 'Tails', ..., 'Head', 'Head', 'Tails'],
       ['Head', 'Head', 'Head', ..., 'Head', 'Tails', 'Tails']],
      dtype='<U5')

In [51]:
boolean_3_heads = [((flips[i] == "Head").sum() == 3) for i in range(0, nrows)]
pd.Series(boolean_3_heads).mean()

0.218159

## 2-b. What is the probability of getting more than 3 heads?

In [52]:
boolean_more_3_heads = [((flips[i] == "Head").sum() > 3) for i in range(0, nrows)]
pd.Series(boolean_more_3_heads).mean()

0.637332

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [69]:
n_trials = nrows = 1_000_000
n_students = ncols = 2
billboards = np.random.choice(['web_development', 'data_science'], 
                              n_trials * n_students, 
                              p = [0.75, 0.25]).reshape(nrows, ncols)
billboards

array([['web_development', 'web_development'],
       ['data_science', 'web_development'],
       ['data_science', 'web_development'],
       ...,
       ['web_development', 'web_development'],
       ['web_development', 'web_development'],
       ['web_development', 'web_development']], dtype='<U15')

In [70]:
boolean = [(billboards[i][0] == 'data_science' and billboards[i][1] == 'data_science') for i in range(0, nrows)]
pd.Series(boolean).mean()

0.062568

## 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [18]:
# Create the matrix 

n_trials = nrows = 1_000_000
n_days = ncols = 4

poptart_bought = np.random.normal(3, 1.5, (n_trials, n_days))
(poptart_bought.sum(axis=1) < 17).mean()

0.952391

## 5. Compare Heights: Men have an average height of 178 cm and standard deviation of 8cm; Women have a mean of 170, sd = 6cm; If a man and woman are chosen at random, P(woman taller than man)?

In [23]:
men = np.random.normal(178, 8, 1_000_000)
women = np.random.normal(170, 6, 1_000_000)
(men < women).mean()

0.211407

## 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
### a. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [32]:
n_trials = nrows = 1_000_000
n_students = 50

installation_50 = np.random.choice(['Success','Fail'], (nrows, n_students), p = [249/250, 1/250])
pd.Series([ 'Fail' not in installation_50[i] for i in range(0, nrows)]).mean()

0.818775

In [33]:
n_trials = nrows = 1_000_000
n_students = 100

installation_50 = np.random.choice(['Success','Fail'], (nrows, n_students), p = [249/250, 1/250])
pd.Series([ 'Fail' not in installation_50[i] for i in range(0, nrows)]).mean()

0.669471

### b. What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [34]:
n_trials = nrows = 1_000_000
n_students = 150

installation_50 = np.random.choice(['Success','Fail'], (nrows, n_students), p = [249/250, 1/250])
pd.Series([ 'Fail' in installation_50[i] for i in range(0, nrows)]).mean()

0.452348

### c. How likely is it that 450 students all download anaconda without an issue?

In [35]:
n_trials = nrows = 1_000_000
n_students = 450

installation_450 = np.random.choice(['Success','Fail'], (nrows, n_students), p = [249/250, 1/250])
pd.Series([ 'Fail' not in installation_450[i] for i in range(0, nrows)]).mean()

0.164735

## 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 

### 7-a However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [46]:
n_trials = nrows = 1_000_000
n_days = ncols = 3

no_food_truck = np.random.choice(['at_least_one','no_show'], (nrows, n_days), p=[0.7, 0.3])
no_food_truck

array([['no_show', 'at_least_one', 'at_least_one'],
       ['at_least_one', 'no_show', 'at_least_one'],
       ['at_least_one', 'at_least_one', 'no_show'],
       ...,
       ['at_least_one', 'no_show', 'no_show'],
       ['at_least_one', 'no_show', 'no_show'],
       ['no_show', 'no_show', 'at_least_one']], dtype='<U12')

In [49]:
pd.Series(['at_least_one' not in no_food_truck[i] for i in range(0, nrows)]).mean()

0.027206

### 7-b. How likely is it that a food truck will show up sometime this week?

In [69]:
n_trials = nrows = 1_000_000
n_days = ncols = 7

food_truck = np.random.choice(['at_least_one','no_show'], (nrows, n_days), p=[0.7, 0.3])
food_truck

array([['at_least_one', 'no_show', 'at_least_one', ..., 'no_show',
        'at_least_one', 'at_least_one'],
       ['no_show', 'no_show', 'at_least_one', ..., 'at_least_one',
        'at_least_one', 'no_show'],
       ['at_least_one', 'at_least_one', 'at_least_one', ...,
        'at_least_one', 'no_show', 'at_least_one'],
       ...,
       ['at_least_one', 'no_show', 'at_least_one', ..., 'at_least_one',
        'at_least_one', 'at_least_one'],
       ['at_least_one', 'at_least_one', 'at_least_one', ..., 'no_show',
        'at_least_one', 'at_least_one'],
       ['at_least_one', 'no_show', 'at_least_one', ..., 'at_least_one',
        'no_show', 'at_least_one']], dtype='<U12')

In [70]:
pd.Series(['at_least_one' in food_truck[i] for i in range(0, nrows)]).mean()

0.999772

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [107]:
n_trials = nrows = 10_000
n_people = ncols = 23

n_birthdays = np.random.choice(range(1,357), (nrows, ncols))
n_birthdays

array([[143,  81, 131, ..., 290, 226, 139],
       [335, 245, 180, ..., 232, 184,  87],
       [209, 194,  41, ..., 268, 253, 196],
       ...,
       [178, 265, 157, ..., 308, 163, 169],
       [ 33,  95, 195, ..., 310, 276, 160],
       [163, 254,  76, ...,  60, 331, 196]])

In [108]:
n_birthdays = pd.DataFrame(n_birthdays)
pd.Series([n_birthdays.iloc[i].duplicated().any() for i in n_birthdays.index]).mean()

0.5105

In [109]:
n_trials = nrows = 10_000
n_people = ncols = 20

n_birthdays = np.random.choice(range(1,357), (nrows, ncols))
n_birthdays

array([[356, 111, 109, ..., 344, 111, 264],
       [148, 116, 202, ..., 226, 251,  26],
       [196, 119,  11, ..., 143, 110, 341],
       ...,
       [265, 218,  89, ...,  46, 158, 309],
       [163, 145, 103, ..., 293, 273, 122],
       [ 83, 318, 323, ...,  83, 146, 287]])

In [123]:
n_birthdays = pd.DataFrame(n_birthdays)
pd.Series([n_birthdays.iloc[i].duplicated().any() for i in n_birthdays.index]).mean()

0.4208

In [137]:
n_trials = nrows = 100_000
n_people = ncols = 40

n_birthdays = np.random.choice(range(1,357), (nrows, ncols))

n_birthdays = pd.DataFrame(n_birthdays)
pd.Series([n_birthdays.iloc[i].duplicated().any() for i in n_birthdays.index]).mean()

0.89707